GET http://localhost:5000/api/category/

###
POST http://localhost:5000/api/category/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2VlNGFjY2Q3ZDI1OTc3MzcxOTcxZDEiLCJ1c2VybmFtZSI6InVzZXIxMjMiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0MzY3NDAzOCwiZXhwIjoxNzQzNjc0NjM4fQ.AntBdVHJnklxx-qUpdJS3Ri7x-IZLd8ibK87BBDvVFk

{
    "name":"Truyen co tich moi"
}

### 
PUT http://localhost:5000/api/category/67ece979beb8a2defe45c812
Content-Type: application/json

{
    "name":"Truyen ngu ngon"
}

###
DELETE http://localhost:5000/api/category/67ece95c4acebbb09925453c
